apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hms
resources:
  - base/ns.yaml
  - base/hms-config-secret.yaml
  - base/deployment.yaml
  - base/service.yaml

labels:
- includeSelectors: true
  pairs:
    ax.platform.component-type: hms-metadata

generatorOptions:
  disableNameSuffixHash: true

