apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-components
  source:
    path: system/nginx-ingress
    repoURL: 'https://github.com/semeteycoskun/lakehouse.git'
    targetRevision: HEAD
  destination:
    namespace: trino
    server: 'https://kubernetes.default.svc'
