apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudbeaver
labels:
- includeSelectors: true
  pairs:
    ax.platform.component-type: mpp-wui
resources:
  - base/ns.yaml
  - base/deployment.yaml
  - base/cb-service.yaml
  - base/initial-conf-secret.yaml
  - base/env-conf-secret.yaml

generatorOptions:
  disableNameSuffixHash: true

#secretGenerator:
#- name: cloudbeaver-conf
#  files:
#  - base/cloudbeaver.conf
#- name: data-sources
#  files:
#  - base/data-sources.json
