apiVersion: v1
kind: Service
metadata:
  labels:
  name: ranger-admin
spec:
  ports:
  - name: http
    port: 6080
    targetPort: 6080
    protocol: TCP
  selector:
    ax.platform.component-type: authz
    ax.platform.component-subtype: authz-admin
  type: ClusterIP
