apiVersion: v1
kind: PersistentVolume
metadata:
  name: strimzi-poc5
  labels:
    ax.platform.component-type: storage
    ax.platform.component-subtype: message-queue
    ax.platform.component-tool: kafka

spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/strimzi-poc5
