apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ranger
labels:
- includeSelectors: true
  pairs:
    ax.platform.component-type: authz-ldap-sync
    ax.platform.component-subtype: authz-ldap-sync
resources:
  - base/ns.yaml
  - base/config-volume.yaml
  - base/deployment.yaml
