kind: Deployment
apiVersion: apps/v1
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: analythinx/ax-hive-metastore:3.1.3v1.0
          ports:
            - containerPort: 9083
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: '100m'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /opt/hive/conf/
              name: hms-config
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: hms-config
          secret:
            defaultMode: 420
            secretName: hms-config-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

