kind: Service
apiVersion: v1
metadata:
  name: hive
  labels:
    app: hive-metastore
spec:
  ports:
    - name: 9083-tcp
      protocol: TCP
      port: 9083
      targetPort: 9083
  selector:
    app: hive-metastore
  type: ClusterIP
