apiVersion: v1
kind: Service
metadata:
  labels:
    development-env: vscode
    platform: ax-lakehouse
  name: vscode-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    development-env: vscode
    platform: ax-lakehouse
  type: ClusterIP

