apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlas
labels:
- includeSelectors: true
  pairs:
    ax.platform.component-type: data-governance
    ax.platform.component-subtype: metadata
resources:
  - base/ns.yaml
  - base/config-volume.yaml
  - base/deployment.yaml
  - base/service.yaml
