apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbeaver-app
  name: cloudbeaver
spec:
  ports:
  - name: http
    port: 8978
    targetPort: 8978
    protocol: TCP
  selector:
  type: ClusterIP
