apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
labels:
- includeSelectors: true
  pairs:
    ax.platform.component-type: metal-loadbalancer


resources:
  - base/metallb-native.yaml
#  - base/pool.yaml
#  - base/advertisement.yaml
