apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakehouse-virtualization
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: lakehouse
  source:
    path: apps/trino
    repoURL: 'https://github.com/analythinx/ax-lakehouse.git'
    targetRevision: HEAD
  destination:
    namespace: trino
    server: 'https://kubernetes.default.svc'
