apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
labels:
- includeSelectors: true
  pairs:
    ax.platform.component-type: ingress-controller-nginx


#helmGlobals:
# chartHome: ./
#
helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx


resources:
  - base/ns.yaml
