apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakehouse-metadata
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: lakehouse
  source:
    path: apps/hms
    repoURL: 'https://github.com/semeteycoskun/lakehouse.git'
    targetRevision: HEAD
  destination:
    namespace: hms
    server: 'https://kubernetes.default.svc'
