apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ranger
labels:
- includeSelectors: true
  pairs:
    ax.platform.component-type: authz
    ax.platform.component-subtype: authz-admin
resources:
  - base/ns.yaml
  - base/config-volume.yaml
  - base/deployment.yaml
  - base/admin-service.yaml
